# baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Software Quality'
theme = 'hugo-book'

enableGitInfo = true
[params]
  BookTheme = 'dark'
  BookToC = true
  BookSection = '*'
  BookRepo = 'https://github.com/uberblah/software-quality'