baseURL = 'https://uberblah.github.io/software-quality'
languageCode = 'en-us'
title = 'Software Quality'
theme = 'hugo-book'

enableGitInfo = true
[params]
  BookTheme = 'dark'  # 'light'
  BookToC = true
  BookSection = '*'
  BookRepo = 'https://github.com/uberblah/software-quality'
  BookEditPath = 'edit/main'
  BookDateFormat = '2006-01-02'